
battle:
    port: 8222
server:
    port: 8202
    tomcat:
        uri-encoding: UTF-8
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.101/magic_war?characterEncoding=UTF-8&useUnicode=true&useSSL=false
        username: root
        password: root123
    kafka:
        producer:
            bootstrap-servers: 192.168.1.101:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
            group-id: test
            bootstrap-servers: 192.168.1.101:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            auto-offset-reset: earliest
    redis:
        host: 192.168.1.101
        port: 6379
        jedis:
            pool:
                max-active: 8
                max-wait: -1
                max-idle: 8
                min-idle: 0
        timeout: 30000
        database: 0

fdfs:
    trackerList:
        - 192.168.1.101:22122
    ## 连接超时时间
    connect-timeout: 15000
    ## 读取inputsream阻塞时间
    so-timeout: 3000
    ## 连接池最大数量
    pool:
        max-total: 200
        ## 每个tracker地址的最大连接数
        max-total-per-key: 20
        ## 连接耗尽时等待获取连接的最大毫秒数
        max-wait-millis: 125000
    ## 缩略图相关配置
    thumbImage:
        height: 150
        width: 150
mybatis:
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.ynhj.magic_war.model
logging:
    level:
        com:
            ynhj:
                magic_war:
                    mapper: debug






