package com.ynhj.magic_war.mapper;

import com.ynhj.magic_war.model.GameDetail;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface GameDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_detail
     *
     * @mbggenerated
     */
    int insert(GameDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_detail
     *
     * @mbggenerated
     */
    int insertSelective(GameDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_detail
     *
     * @mbggenerated
     */
    GameDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GameDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GameDetail record);
}