package com.ynhj.magic_war.mapper;

import com.ynhj.magic_war.model.RoleSkill;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface RoleSkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_skill
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_skill
     *
     * @mbggenerated
     */
    int insert(RoleSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_skill
     *
     * @mbggenerated
     */
    int insertSelective(RoleSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_skill
     *
     * @mbggenerated
     */
    RoleSkill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_skill
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_skill
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleSkill record);
}