package com.ynhj.magic_war.mapper;

import com.ynhj.magic_war.model.RoleEquipment;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface RoleEquipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_equipment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_equipment
     *
     * @mbggenerated
     */
    int insert(RoleEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_equipment
     *
     * @mbggenerated
     */
    int insertSelective(RoleEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_equipment
     *
     * @mbggenerated
     */
    RoleEquipment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_equipment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_equipment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleEquipment record);
}