package com.ynhj.magic_war.mapper;

import com.ynhj.magic_war.model.UserUser;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user-user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user-user
     *
     * @mbggenerated
     */
    int insert(UserUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user-user
     *
     * @mbggenerated
     */
    int insertSelective(UserUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user-user
     *
     * @mbggenerated
     */
    UserUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user-user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user-user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserUser record);
}