package com.ynhj.magic_war.model.entity.msg.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/HitMsg.proto

public final class HitMsgOuterClass {
  private HitMsgOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HitMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HitMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <code>string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>int32 skillId = 2;</code>
     */
    int getSkillId();

    /**
     * <code>float x = 3;</code>
     */
    float getX();

    /**
     * <code>float z = 4;</code>
     */
    float getZ();

    /**
     * <code>float y = 5;</code>
     */
    float getY();

    /**
     * <code>string targetId = 6;</code>
     */
    java.lang.String getTargetId();
    /**
     * <code>string targetId = 6;</code>
     */
    com.google.protobuf.ByteString
        getTargetIdBytes();
  }
  /**
   * Protobuf type {@code HitMsg}
   */
  public  static final class HitMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HitMsg)
      HitMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HitMsg.newBuilder() to construct.
    private HitMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HitMsg() {
      uid_ = "";
      skillId_ = 0;
      x_ = 0F;
      z_ = 0F;
      y_ = 0F;
      targetId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HitMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 16: {

              skillId_ = input.readInt32();
              break;
            }
            case 29: {

              x_ = input.readFloat();
              break;
            }
            case 37: {

              z_ = input.readFloat();
              break;
            }
            case 45: {

              y_ = input.readFloat();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              targetId_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HitMsgOuterClass.internal_static_HitMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HitMsgOuterClass.internal_static_HitMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HitMsgOuterClass.HitMsg.class, HitMsgOuterClass.HitMsg.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <code>string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <code>string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SKILLID_FIELD_NUMBER = 2;
    private int skillId_;
    /**
     * <code>int32 skillId = 2;</code>
     */
    public int getSkillId() {
      return skillId_;
    }

    public static final int X_FIELD_NUMBER = 3;
    private float x_;
    /**
     * <code>float x = 3;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Z_FIELD_NUMBER = 4;
    private float z_;
    /**
     * <code>float z = 4;</code>
     */
    public float getZ() {
      return z_;
    }

    public static final int Y_FIELD_NUMBER = 5;
    private float y_;
    /**
     * <code>float y = 5;</code>
     */
    public float getY() {
      return y_;
    }

    public static final int TARGETID_FIELD_NUMBER = 6;
    private volatile java.lang.Object targetId_;
    /**
     * <code>string targetId = 6;</code>
     */
    public java.lang.String getTargetId() {
      java.lang.Object ref = targetId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetId_ = s;
        return s;
      }
    }
    /**
     * <code>string targetId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTargetIdBytes() {
      java.lang.Object ref = targetId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (skillId_ != 0) {
        output.writeInt32(2, skillId_);
      }
      if (x_ != 0F) {
        output.writeFloat(3, x_);
      }
      if (z_ != 0F) {
        output.writeFloat(4, z_);
      }
      if (y_ != 0F) {
        output.writeFloat(5, y_);
      }
      if (!getTargetIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, targetId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (skillId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, skillId_);
      }
      if (x_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, x_);
      }
      if (z_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, z_);
      }
      if (y_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, y_);
      }
      if (!getTargetIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, targetId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HitMsgOuterClass.HitMsg)) {
        return super.equals(obj);
      }
      HitMsgOuterClass.HitMsg other = (HitMsgOuterClass.HitMsg) obj;

      boolean result = true;
      result = result && getUid()
          .equals(other.getUid());
      result = result && (getSkillId()
          == other.getSkillId());
      result = result && (
          java.lang.Float.floatToIntBits(getX())
          == java.lang.Float.floatToIntBits(
              other.getX()));
      result = result && (
          java.lang.Float.floatToIntBits(getZ())
          == java.lang.Float.floatToIntBits(
              other.getZ()));
      result = result && (
          java.lang.Float.floatToIntBits(getY())
          == java.lang.Float.floatToIntBits(
              other.getY()));
      result = result && getTargetId()
          .equals(other.getTargetId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + SKILLID_FIELD_NUMBER;
      hash = (53 * hash) + getSkillId();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getX());
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getZ());
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getY());
      hash = (37 * hash) + TARGETID_FIELD_NUMBER;
      hash = (53 * hash) + getTargetId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HitMsgOuterClass.HitMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HitMsgOuterClass.HitMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HitMsgOuterClass.HitMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HitMsgOuterClass.HitMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HitMsgOuterClass.HitMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HitMsgOuterClass.HitMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HitMsgOuterClass.HitMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HitMsgOuterClass.HitMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HitMsgOuterClass.HitMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HitMsgOuterClass.HitMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HitMsgOuterClass.HitMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HitMsgOuterClass.HitMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HitMsgOuterClass.HitMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HitMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HitMsg)
        HitMsgOuterClass.HitMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HitMsgOuterClass.internal_static_HitMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HitMsgOuterClass.internal_static_HitMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HitMsgOuterClass.HitMsg.class, HitMsgOuterClass.HitMsg.Builder.class);
      }

      // Construct using HitMsgOuterClass.HitMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = "";

        skillId_ = 0;

        x_ = 0F;

        z_ = 0F;

        y_ = 0F;

        targetId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HitMsgOuterClass.internal_static_HitMsg_descriptor;
      }

      @java.lang.Override
      public HitMsgOuterClass.HitMsg getDefaultInstanceForType() {
        return HitMsgOuterClass.HitMsg.getDefaultInstance();
      }

      @java.lang.Override
      public HitMsgOuterClass.HitMsg build() {
        HitMsgOuterClass.HitMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public HitMsgOuterClass.HitMsg buildPartial() {
        HitMsgOuterClass.HitMsg result = new HitMsgOuterClass.HitMsg(this);
        result.uid_ = uid_;
        result.skillId_ = skillId_;
        result.x_ = x_;
        result.z_ = z_;
        result.y_ = y_;
        result.targetId_ = targetId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HitMsgOuterClass.HitMsg) {
          return mergeFrom((HitMsgOuterClass.HitMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HitMsgOuterClass.HitMsg other) {
        if (other == HitMsgOuterClass.HitMsg.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (other.getSkillId() != 0) {
          setSkillId(other.getSkillId());
        }
        if (other.getX() != 0F) {
          setX(other.getX());
        }
        if (other.getZ() != 0F) {
          setZ(other.getZ());
        }
        if (other.getY() != 0F) {
          setY(other.getY());
        }
        if (!other.getTargetId().isEmpty()) {
          targetId_ = other.targetId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HitMsgOuterClass.HitMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HitMsgOuterClass.HitMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <code>string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }

      private int skillId_ ;
      /**
       * <code>int32 skillId = 2;</code>
       */
      public int getSkillId() {
        return skillId_;
      }
      /**
       * <code>int32 skillId = 2;</code>
       */
      public Builder setSkillId(int value) {
        
        skillId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 skillId = 2;</code>
       */
      public Builder clearSkillId() {
        
        skillId_ = 0;
        onChanged();
        return this;
      }

      private float x_ ;
      /**
       * <code>float x = 3;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>float x = 3;</code>
       */
      public Builder setX(float value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float x = 3;</code>
       */
      public Builder clearX() {
        
        x_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>float z = 4;</code>
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>float z = 4;</code>
       */
      public Builder setZ(float value) {
        
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float z = 4;</code>
       */
      public Builder clearZ() {
        
        z_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>float y = 5;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>float y = 5;</code>
       */
      public Builder setY(float value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float y = 5;</code>
       */
      public Builder clearY() {
        
        y_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object targetId_ = "";
      /**
       * <code>string targetId = 6;</code>
       */
      public java.lang.String getTargetId() {
        java.lang.Object ref = targetId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          targetId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string targetId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTargetIdBytes() {
        java.lang.Object ref = targetId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string targetId = 6;</code>
       */
      public Builder setTargetId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        targetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string targetId = 6;</code>
       */
      public Builder clearTargetId() {
        
        targetId_ = getDefaultInstance().getTargetId();
        onChanged();
        return this;
      }
      /**
       * <code>string targetId = 6;</code>
       */
      public Builder setTargetIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        targetId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HitMsg)
    }

    // @@protoc_insertion_point(class_scope:HitMsg)
    private static final HitMsgOuterClass.HitMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HitMsgOuterClass.HitMsg();
    }

    public static HitMsgOuterClass.HitMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HitMsg>
        PARSER = new com.google.protobuf.AbstractParser<HitMsg>() {
      @java.lang.Override
      public HitMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HitMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HitMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HitMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public HitMsgOuterClass.HitMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HitMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HitMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022proto/HitMsg.proto\"Y\n\006HitMsg\022\013\n\003uid\030\001 " +
      "\001(\t\022\017\n\007skillId\030\002 \001(\005\022\t\n\001x\030\003 \001(\002\022\t\n\001z\030\004 \001" +
      "(\002\022\t\n\001y\030\005 \001(\002\022\020\n\010targetId\030\006 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HitMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HitMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HitMsg_descriptor,
        new java.lang.String[] { "Uid", "SkillId", "X", "Z", "Y", "TargetId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
