package com.ynhj.magic_war.model.entity.msg.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SkillMsg.proto

public final class SkillMsgOuterClass {
  private SkillMsgOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SkillMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SkillMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <code>string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>int32 skillId = 2;</code>
     */
    int getSkillId();

    /**
     * <code>float x = 3;</code>
     */
    float getX();

    /**
     * <code>float y = 4;</code>
     */
    float getY();

    /**
     * <code>float z = 5;</code>
     */
    float getZ();

    /**
     * <code>float ex = 6;</code>
     */
    float getEx();

    /**
     * <code>float ey = 7;</code>
     */
    float getEy();

    /**
     * <code>float ez = 8;</code>
     */
    float getEz();
  }
  /**
   * Protobuf type {@code SkillMsg}
   */
  public  static final class SkillMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SkillMsg)
      SkillMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SkillMsg.newBuilder() to construct.
    private SkillMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SkillMsg() {
      uid_ = "";
      skillId_ = 0;
      x_ = 0F;
      y_ = 0F;
      z_ = 0F;
      ex_ = 0F;
      ey_ = 0F;
      ez_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SkillMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 16: {

              skillId_ = input.readInt32();
              break;
            }
            case 29: {

              x_ = input.readFloat();
              break;
            }
            case 37: {

              y_ = input.readFloat();
              break;
            }
            case 45: {

              z_ = input.readFloat();
              break;
            }
            case 53: {

              ex_ = input.readFloat();
              break;
            }
            case 61: {

              ey_ = input.readFloat();
              break;
            }
            case 69: {

              ez_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SkillMsgOuterClass.internal_static_SkillMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SkillMsgOuterClass.internal_static_SkillMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SkillMsgOuterClass.SkillMsg.class, SkillMsgOuterClass.SkillMsg.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <code>string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <code>string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SKILLID_FIELD_NUMBER = 2;
    private int skillId_;
    /**
     * <code>int32 skillId = 2;</code>
     */
    public int getSkillId() {
      return skillId_;
    }

    public static final int X_FIELD_NUMBER = 3;
    private float x_;
    /**
     * <code>float x = 3;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 4;
    private float y_;
    /**
     * <code>float y = 4;</code>
     */
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 5;
    private float z_;
    /**
     * <code>float z = 5;</code>
     */
    public float getZ() {
      return z_;
    }

    public static final int EX_FIELD_NUMBER = 6;
    private float ex_;
    /**
     * <code>float ex = 6;</code>
     */
    public float getEx() {
      return ex_;
    }

    public static final int EY_FIELD_NUMBER = 7;
    private float ey_;
    /**
     * <code>float ey = 7;</code>
     */
    public float getEy() {
      return ey_;
    }

    public static final int EZ_FIELD_NUMBER = 8;
    private float ez_;
    /**
     * <code>float ez = 8;</code>
     */
    public float getEz() {
      return ez_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (skillId_ != 0) {
        output.writeInt32(2, skillId_);
      }
      if (x_ != 0F) {
        output.writeFloat(3, x_);
      }
      if (y_ != 0F) {
        output.writeFloat(4, y_);
      }
      if (z_ != 0F) {
        output.writeFloat(5, z_);
      }
      if (ex_ != 0F) {
        output.writeFloat(6, ex_);
      }
      if (ey_ != 0F) {
        output.writeFloat(7, ey_);
      }
      if (ez_ != 0F) {
        output.writeFloat(8, ez_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (skillId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, skillId_);
      }
      if (x_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, x_);
      }
      if (y_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, y_);
      }
      if (z_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, z_);
      }
      if (ex_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, ex_);
      }
      if (ey_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, ey_);
      }
      if (ez_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, ez_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SkillMsgOuterClass.SkillMsg)) {
        return super.equals(obj);
      }
      SkillMsgOuterClass.SkillMsg other = (SkillMsgOuterClass.SkillMsg) obj;

      boolean result = true;
      result = result && getUid()
          .equals(other.getUid());
      result = result && (getSkillId()
          == other.getSkillId());
      result = result && (
          java.lang.Float.floatToIntBits(getX())
          == java.lang.Float.floatToIntBits(
              other.getX()));
      result = result && (
          java.lang.Float.floatToIntBits(getY())
          == java.lang.Float.floatToIntBits(
              other.getY()));
      result = result && (
          java.lang.Float.floatToIntBits(getZ())
          == java.lang.Float.floatToIntBits(
              other.getZ()));
      result = result && (
          java.lang.Float.floatToIntBits(getEx())
          == java.lang.Float.floatToIntBits(
              other.getEx()));
      result = result && (
          java.lang.Float.floatToIntBits(getEy())
          == java.lang.Float.floatToIntBits(
              other.getEy()));
      result = result && (
          java.lang.Float.floatToIntBits(getEz())
          == java.lang.Float.floatToIntBits(
              other.getEz()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + SKILLID_FIELD_NUMBER;
      hash = (53 * hash) + getSkillId();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getX());
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getY());
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getZ());
      hash = (37 * hash) + EX_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getEx());
      hash = (37 * hash) + EY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getEy());
      hash = (37 * hash) + EZ_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getEz());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SkillMsgOuterClass.SkillMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SkillMsgOuterClass.SkillMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SkillMsgOuterClass.SkillMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SkillMsgOuterClass.SkillMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SkillMsgOuterClass.SkillMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SkillMsgOuterClass.SkillMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SkillMsgOuterClass.SkillMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SkillMsgOuterClass.SkillMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SkillMsgOuterClass.SkillMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SkillMsgOuterClass.SkillMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SkillMsgOuterClass.SkillMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SkillMsgOuterClass.SkillMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SkillMsgOuterClass.SkillMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SkillMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SkillMsg)
        SkillMsgOuterClass.SkillMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SkillMsgOuterClass.internal_static_SkillMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SkillMsgOuterClass.internal_static_SkillMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SkillMsgOuterClass.SkillMsg.class, SkillMsgOuterClass.SkillMsg.Builder.class);
      }

      // Construct using SkillMsgOuterClass.SkillMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = "";

        skillId_ = 0;

        x_ = 0F;

        y_ = 0F;

        z_ = 0F;

        ex_ = 0F;

        ey_ = 0F;

        ez_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SkillMsgOuterClass.internal_static_SkillMsg_descriptor;
      }

      @java.lang.Override
      public SkillMsgOuterClass.SkillMsg getDefaultInstanceForType() {
        return SkillMsgOuterClass.SkillMsg.getDefaultInstance();
      }

      @java.lang.Override
      public SkillMsgOuterClass.SkillMsg build() {
        SkillMsgOuterClass.SkillMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SkillMsgOuterClass.SkillMsg buildPartial() {
        SkillMsgOuterClass.SkillMsg result = new SkillMsgOuterClass.SkillMsg(this);
        result.uid_ = uid_;
        result.skillId_ = skillId_;
        result.x_ = x_;
        result.y_ = y_;
        result.z_ = z_;
        result.ex_ = ex_;
        result.ey_ = ey_;
        result.ez_ = ez_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SkillMsgOuterClass.SkillMsg) {
          return mergeFrom((SkillMsgOuterClass.SkillMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SkillMsgOuterClass.SkillMsg other) {
        if (other == SkillMsgOuterClass.SkillMsg.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (other.getSkillId() != 0) {
          setSkillId(other.getSkillId());
        }
        if (other.getX() != 0F) {
          setX(other.getX());
        }
        if (other.getY() != 0F) {
          setY(other.getY());
        }
        if (other.getZ() != 0F) {
          setZ(other.getZ());
        }
        if (other.getEx() != 0F) {
          setEx(other.getEx());
        }
        if (other.getEy() != 0F) {
          setEy(other.getEy());
        }
        if (other.getEz() != 0F) {
          setEz(other.getEz());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SkillMsgOuterClass.SkillMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SkillMsgOuterClass.SkillMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <code>string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }

      private int skillId_ ;
      /**
       * <code>int32 skillId = 2;</code>
       */
      public int getSkillId() {
        return skillId_;
      }
      /**
       * <code>int32 skillId = 2;</code>
       */
      public Builder setSkillId(int value) {
        
        skillId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 skillId = 2;</code>
       */
      public Builder clearSkillId() {
        
        skillId_ = 0;
        onChanged();
        return this;
      }

      private float x_ ;
      /**
       * <code>float x = 3;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>float x = 3;</code>
       */
      public Builder setX(float value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float x = 3;</code>
       */
      public Builder clearX() {
        
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>float y = 4;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>float y = 4;</code>
       */
      public Builder setY(float value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float y = 4;</code>
       */
      public Builder clearY() {
        
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>float z = 5;</code>
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>float z = 5;</code>
       */
      public Builder setZ(float value) {
        
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float z = 5;</code>
       */
      public Builder clearZ() {
        
        z_ = 0F;
        onChanged();
        return this;
      }

      private float ex_ ;
      /**
       * <code>float ex = 6;</code>
       */
      public float getEx() {
        return ex_;
      }
      /**
       * <code>float ex = 6;</code>
       */
      public Builder setEx(float value) {
        
        ex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float ex = 6;</code>
       */
      public Builder clearEx() {
        
        ex_ = 0F;
        onChanged();
        return this;
      }

      private float ey_ ;
      /**
       * <code>float ey = 7;</code>
       */
      public float getEy() {
        return ey_;
      }
      /**
       * <code>float ey = 7;</code>
       */
      public Builder setEy(float value) {
        
        ey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float ey = 7;</code>
       */
      public Builder clearEy() {
        
        ey_ = 0F;
        onChanged();
        return this;
      }

      private float ez_ ;
      /**
       * <code>float ez = 8;</code>
       */
      public float getEz() {
        return ez_;
      }
      /**
       * <code>float ez = 8;</code>
       */
      public Builder setEz(float value) {
        
        ez_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float ez = 8;</code>
       */
      public Builder clearEz() {
        
        ez_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SkillMsg)
    }

    // @@protoc_insertion_point(class_scope:SkillMsg)
    private static final SkillMsgOuterClass.SkillMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SkillMsgOuterClass.SkillMsg();
    }

    public static SkillMsgOuterClass.SkillMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SkillMsg>
        PARSER = new com.google.protobuf.AbstractParser<SkillMsg>() {
      @java.lang.Override
      public SkillMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SkillMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SkillMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SkillMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SkillMsgOuterClass.SkillMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SkillMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SkillMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024proto/SkillMsg.proto\"m\n\010SkillMsg\022\013\n\003ui" +
      "d\030\001 \001(\t\022\017\n\007skillId\030\002 \001(\005\022\t\n\001x\030\003 \001(\002\022\t\n\001y" +
      "\030\004 \001(\002\022\t\n\001z\030\005 \001(\002\022\n\n\002ex\030\006 \001(\002\022\n\n\002ey\030\007 \001(" +
      "\002\022\n\n\002ez\030\010 \001(\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SkillMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SkillMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SkillMsg_descriptor,
        new java.lang.String[] { "Uid", "SkillId", "X", "Y", "Z", "Ex", "Ey", "Ez", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
