package com.ynhj.magic_war.model.entity.msg.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SyncPlayerMsg.proto

public final class SyncPlayerMsgOuterClass {
  private SyncPlayerMsgOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SyncPlayerMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SyncPlayerMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <code>string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>float x = 2;</code>
     */
    float getX();

    /**
     * <code>float z = 3;</code>
     */
    float getZ();

    /**
     * <code>float ey = 4;</code>
     */
    float getEy();

    /**
     * <code>double hp = 5;</code>
     */
    double getHp();

    /**
     * <code>double speed = 6;</code>
     */
    double getSpeed();

    /**
     * <code>int32 killNum = 7;</code>
     */
    int getKillNum();

    /**
     * <code>int64 frame = 8;</code>
     */
    long getFrame();
  }
  /**
   * Protobuf type {@code SyncPlayerMsg}
   */
  public  static final class SyncPlayerMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SyncPlayerMsg)
      SyncPlayerMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SyncPlayerMsg.newBuilder() to construct.
    private SyncPlayerMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SyncPlayerMsg() {
      uid_ = "";
      x_ = 0F;
      z_ = 0F;
      ey_ = 0F;
      hp_ = 0D;
      speed_ = 0D;
      killNum_ = 0;
      frame_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SyncPlayerMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 21: {

              x_ = input.readFloat();
              break;
            }
            case 29: {

              z_ = input.readFloat();
              break;
            }
            case 37: {

              ey_ = input.readFloat();
              break;
            }
            case 41: {

              hp_ = input.readDouble();
              break;
            }
            case 49: {

              speed_ = input.readDouble();
              break;
            }
            case 56: {

              killNum_ = input.readInt32();
              break;
            }
            case 64: {

              frame_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SyncPlayerMsgOuterClass.internal_static_SyncPlayerMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SyncPlayerMsgOuterClass.internal_static_SyncPlayerMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SyncPlayerMsgOuterClass.SyncPlayerMsg.class, SyncPlayerMsgOuterClass.SyncPlayerMsg.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <code>string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <code>string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int X_FIELD_NUMBER = 2;
    private float x_;
    /**
     * <code>float x = 2;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_;
    /**
     * <code>float z = 3;</code>
     */
    public float getZ() {
      return z_;
    }

    public static final int EY_FIELD_NUMBER = 4;
    private float ey_;
    /**
     * <code>float ey = 4;</code>
     */
    public float getEy() {
      return ey_;
    }

    public static final int HP_FIELD_NUMBER = 5;
    private double hp_;
    /**
     * <code>double hp = 5;</code>
     */
    public double getHp() {
      return hp_;
    }

    public static final int SPEED_FIELD_NUMBER = 6;
    private double speed_;
    /**
     * <code>double speed = 6;</code>
     */
    public double getSpeed() {
      return speed_;
    }

    public static final int KILLNUM_FIELD_NUMBER = 7;
    private int killNum_;
    /**
     * <code>int32 killNum = 7;</code>
     */
    public int getKillNum() {
      return killNum_;
    }

    public static final int FRAME_FIELD_NUMBER = 8;
    private long frame_;
    /**
     * <code>int64 frame = 8;</code>
     */
    public long getFrame() {
      return frame_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (x_ != 0F) {
        output.writeFloat(2, x_);
      }
      if (z_ != 0F) {
        output.writeFloat(3, z_);
      }
      if (ey_ != 0F) {
        output.writeFloat(4, ey_);
      }
      if (hp_ != 0D) {
        output.writeDouble(5, hp_);
      }
      if (speed_ != 0D) {
        output.writeDouble(6, speed_);
      }
      if (killNum_ != 0) {
        output.writeInt32(7, killNum_);
      }
      if (frame_ != 0L) {
        output.writeInt64(8, frame_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (x_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, x_);
      }
      if (z_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      if (ey_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, ey_);
      }
      if (hp_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, hp_);
      }
      if (speed_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, speed_);
      }
      if (killNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, killNum_);
      }
      if (frame_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, frame_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SyncPlayerMsgOuterClass.SyncPlayerMsg)) {
        return super.equals(obj);
      }
      SyncPlayerMsgOuterClass.SyncPlayerMsg other = (SyncPlayerMsgOuterClass.SyncPlayerMsg) obj;

      boolean result = true;
      result = result && getUid()
          .equals(other.getUid());
      result = result && (
          java.lang.Float.floatToIntBits(getX())
          == java.lang.Float.floatToIntBits(
              other.getX()));
      result = result && (
          java.lang.Float.floatToIntBits(getZ())
          == java.lang.Float.floatToIntBits(
              other.getZ()));
      result = result && (
          java.lang.Float.floatToIntBits(getEy())
          == java.lang.Float.floatToIntBits(
              other.getEy()));
      result = result && (
          java.lang.Double.doubleToLongBits(getHp())
          == java.lang.Double.doubleToLongBits(
              other.getHp()));
      result = result && (
          java.lang.Double.doubleToLongBits(getSpeed())
          == java.lang.Double.doubleToLongBits(
              other.getSpeed()));
      result = result && (getKillNum()
          == other.getKillNum());
      result = result && (getFrame()
          == other.getFrame());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getX());
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getZ());
      hash = (37 * hash) + EY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getEy());
      hash = (37 * hash) + HP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getHp()));
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSpeed()));
      hash = (37 * hash) + KILLNUM_FIELD_NUMBER;
      hash = (53 * hash) + getKillNum();
      hash = (37 * hash) + FRAME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFrame());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SyncPlayerMsgOuterClass.SyncPlayerMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SyncPlayerMsgOuterClass.SyncPlayerMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SyncPlayerMsgOuterClass.SyncPlayerMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SyncPlayerMsgOuterClass.SyncPlayerMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SyncPlayerMsgOuterClass.SyncPlayerMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SyncPlayerMsgOuterClass.SyncPlayerMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SyncPlayerMsgOuterClass.SyncPlayerMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SyncPlayerMsgOuterClass.SyncPlayerMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SyncPlayerMsgOuterClass.SyncPlayerMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SyncPlayerMsgOuterClass.SyncPlayerMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SyncPlayerMsgOuterClass.SyncPlayerMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SyncPlayerMsgOuterClass.SyncPlayerMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SyncPlayerMsgOuterClass.SyncPlayerMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SyncPlayerMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SyncPlayerMsg)
        SyncPlayerMsgOuterClass.SyncPlayerMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SyncPlayerMsgOuterClass.internal_static_SyncPlayerMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SyncPlayerMsgOuterClass.internal_static_SyncPlayerMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SyncPlayerMsgOuterClass.SyncPlayerMsg.class, SyncPlayerMsgOuterClass.SyncPlayerMsg.Builder.class);
      }

      // Construct using SyncPlayerMsgOuterClass.SyncPlayerMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = "";

        x_ = 0F;

        z_ = 0F;

        ey_ = 0F;

        hp_ = 0D;

        speed_ = 0D;

        killNum_ = 0;

        frame_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SyncPlayerMsgOuterClass.internal_static_SyncPlayerMsg_descriptor;
      }

      @java.lang.Override
      public SyncPlayerMsgOuterClass.SyncPlayerMsg getDefaultInstanceForType() {
        return SyncPlayerMsgOuterClass.SyncPlayerMsg.getDefaultInstance();
      }

      @java.lang.Override
      public SyncPlayerMsgOuterClass.SyncPlayerMsg build() {
        SyncPlayerMsgOuterClass.SyncPlayerMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SyncPlayerMsgOuterClass.SyncPlayerMsg buildPartial() {
        SyncPlayerMsgOuterClass.SyncPlayerMsg result = new SyncPlayerMsgOuterClass.SyncPlayerMsg(this);
        result.uid_ = uid_;
        result.x_ = x_;
        result.z_ = z_;
        result.ey_ = ey_;
        result.hp_ = hp_;
        result.speed_ = speed_;
        result.killNum_ = killNum_;
        result.frame_ = frame_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SyncPlayerMsgOuterClass.SyncPlayerMsg) {
          return mergeFrom((SyncPlayerMsgOuterClass.SyncPlayerMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SyncPlayerMsgOuterClass.SyncPlayerMsg other) {
        if (other == SyncPlayerMsgOuterClass.SyncPlayerMsg.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (other.getX() != 0F) {
          setX(other.getX());
        }
        if (other.getZ() != 0F) {
          setZ(other.getZ());
        }
        if (other.getEy() != 0F) {
          setEy(other.getEy());
        }
        if (other.getHp() != 0D) {
          setHp(other.getHp());
        }
        if (other.getSpeed() != 0D) {
          setSpeed(other.getSpeed());
        }
        if (other.getKillNum() != 0) {
          setKillNum(other.getKillNum());
        }
        if (other.getFrame() != 0L) {
          setFrame(other.getFrame());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SyncPlayerMsgOuterClass.SyncPlayerMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SyncPlayerMsgOuterClass.SyncPlayerMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <code>string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }

      private float x_ ;
      /**
       * <code>float x = 2;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>float x = 2;</code>
       */
      public Builder setX(float value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float x = 2;</code>
       */
      public Builder clearX() {
        
        x_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>float z = 3;</code>
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>float z = 3;</code>
       */
      public Builder setZ(float value) {
        
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float z = 3;</code>
       */
      public Builder clearZ() {
        
        z_ = 0F;
        onChanged();
        return this;
      }

      private float ey_ ;
      /**
       * <code>float ey = 4;</code>
       */
      public float getEy() {
        return ey_;
      }
      /**
       * <code>float ey = 4;</code>
       */
      public Builder setEy(float value) {
        
        ey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float ey = 4;</code>
       */
      public Builder clearEy() {
        
        ey_ = 0F;
        onChanged();
        return this;
      }

      private double hp_ ;
      /**
       * <code>double hp = 5;</code>
       */
      public double getHp() {
        return hp_;
      }
      /**
       * <code>double hp = 5;</code>
       */
      public Builder setHp(double value) {
        
        hp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double hp = 5;</code>
       */
      public Builder clearHp() {
        
        hp_ = 0D;
        onChanged();
        return this;
      }

      private double speed_ ;
      /**
       * <code>double speed = 6;</code>
       */
      public double getSpeed() {
        return speed_;
      }
      /**
       * <code>double speed = 6;</code>
       */
      public Builder setSpeed(double value) {
        
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double speed = 6;</code>
       */
      public Builder clearSpeed() {
        
        speed_ = 0D;
        onChanged();
        return this;
      }

      private int killNum_ ;
      /**
       * <code>int32 killNum = 7;</code>
       */
      public int getKillNum() {
        return killNum_;
      }
      /**
       * <code>int32 killNum = 7;</code>
       */
      public Builder setKillNum(int value) {
        
        killNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 killNum = 7;</code>
       */
      public Builder clearKillNum() {
        
        killNum_ = 0;
        onChanged();
        return this;
      }

      private long frame_ ;
      /**
       * <code>int64 frame = 8;</code>
       */
      public long getFrame() {
        return frame_;
      }
      /**
       * <code>int64 frame = 8;</code>
       */
      public Builder setFrame(long value) {
        
        frame_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 frame = 8;</code>
       */
      public Builder clearFrame() {
        
        frame_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SyncPlayerMsg)
    }

    // @@protoc_insertion_point(class_scope:SyncPlayerMsg)
    private static final SyncPlayerMsgOuterClass.SyncPlayerMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SyncPlayerMsgOuterClass.SyncPlayerMsg();
    }

    public static SyncPlayerMsgOuterClass.SyncPlayerMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SyncPlayerMsg>
        PARSER = new com.google.protobuf.AbstractParser<SyncPlayerMsg>() {
      @java.lang.Override
      public SyncPlayerMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SyncPlayerMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SyncPlayerMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SyncPlayerMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SyncPlayerMsgOuterClass.SyncPlayerMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SyncPlayerMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SyncPlayerMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031proto/SyncPlayerMsg.proto\"y\n\rSyncPlaye" +
      "rMsg\022\013\n\003uid\030\001 \001(\t\022\t\n\001x\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\022" +
      "\n\n\002ey\030\004 \001(\002\022\n\n\002hp\030\005 \001(\001\022\r\n\005speed\030\006 \001(\001\022\017" +
      "\n\007killNum\030\007 \001(\005\022\r\n\005frame\030\010 \001(\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SyncPlayerMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SyncPlayerMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SyncPlayerMsg_descriptor,
        new java.lang.String[] { "Uid", "X", "Z", "Ey", "Hp", "Speed", "KillNum", "Frame", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
