package com.ynhj.magic_war.model;

import java.util.Date;

public class Equipment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.hp
     *
     * @mbggenerated
     */
    private Integer hp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.mp
     *
     * @mbggenerated
     */
    private Integer mp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.attach
     *
     * @mbggenerated
     */
    private Double attach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.defense
     *
     * @mbggenerated
     */
    private Double defense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.speed
     *
     * @mbggenerated
     */
    private Double speed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.preb_url
     *
     * @mbggenerated
     */
    private String prebUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.ui_rul
     *
     * @mbggenerated
     */
    private String uiRul;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.id
     *
     * @return the value of equipment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.id
     *
     * @param id the value for equipment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.hp
     *
     * @return the value of equipment.hp
     *
     * @mbggenerated
     */
    public Integer getHp() {
        return hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.hp
     *
     * @param hp the value for equipment.hp
     *
     * @mbggenerated
     */
    public void setHp(Integer hp) {
        this.hp = hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.mp
     *
     * @return the value of equipment.mp
     *
     * @mbggenerated
     */
    public Integer getMp() {
        return mp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.mp
     *
     * @param mp the value for equipment.mp
     *
     * @mbggenerated
     */
    public void setMp(Integer mp) {
        this.mp = mp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.attach
     *
     * @return the value of equipment.attach
     *
     * @mbggenerated
     */
    public Double getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.attach
     *
     * @param attach the value for equipment.attach
     *
     * @mbggenerated
     */
    public void setAttach(Double attach) {
        this.attach = attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.defense
     *
     * @return the value of equipment.defense
     *
     * @mbggenerated
     */
    public Double getDefense() {
        return defense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.defense
     *
     * @param defense the value for equipment.defense
     *
     * @mbggenerated
     */
    public void setDefense(Double defense) {
        this.defense = defense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.speed
     *
     * @return the value of equipment.speed
     *
     * @mbggenerated
     */
    public Double getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.speed
     *
     * @param speed the value for equipment.speed
     *
     * @mbggenerated
     */
    public void setSpeed(Double speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.name
     *
     * @return the value of equipment.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.name
     *
     * @param name the value for equipment.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.create_time
     *
     * @return the value of equipment.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.create_time
     *
     * @param createTime the value for equipment.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.create_user
     *
     * @return the value of equipment.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.create_user
     *
     * @param createUser the value for equipment.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.update_time
     *
     * @return the value of equipment.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.update_time
     *
     * @param updateTime the value for equipment.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.update_user
     *
     * @return the value of equipment.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.update_user
     *
     * @param updateUser the value for equipment.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.preb_url
     *
     * @return the value of equipment.preb_url
     *
     * @mbggenerated
     */
    public String getPrebUrl() {
        return prebUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.preb_url
     *
     * @param prebUrl the value for equipment.preb_url
     *
     * @mbggenerated
     */
    public void setPrebUrl(String prebUrl) {
        this.prebUrl = prebUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.ui_rul
     *
     * @return the value of equipment.ui_rul
     *
     * @mbggenerated
     */
    public String getUiRul() {
        return uiRul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.ui_rul
     *
     * @param uiRul the value for equipment.ui_rul
     *
     * @mbggenerated
     */
    public void setUiRul(String uiRul) {
        this.uiRul = uiRul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.type
     *
     * @return the value of equipment.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.type
     *
     * @param type the value for equipment.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.status
     *
     * @return the value of equipment.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.status
     *
     * @param status the value for equipment.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }
}