package com.ynhj.magic_war.model;

public class GameDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_detail.game_id
     *
     * @mbggenerated
     */
    private Integer gameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_detail.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_detail.kill_num
     *
     * @mbggenerated
     */
    private Integer killNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_detail.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_detail.rank
     *
     * @mbggenerated
     */
    private Integer rank;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_detail.id
     *
     * @return the value of game_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_detail.id
     *
     * @param id the value for game_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_detail.game_id
     *
     * @return the value of game_detail.game_id
     *
     * @mbggenerated
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_detail.game_id
     *
     * @param gameId the value for game_detail.game_id
     *
     * @mbggenerated
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_detail.role_id
     *
     * @return the value of game_detail.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_detail.role_id
     *
     * @param roleId the value for game_detail.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_detail.kill_num
     *
     * @return the value of game_detail.kill_num
     *
     * @mbggenerated
     */
    public Integer getKillNum() {
        return killNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_detail.kill_num
     *
     * @param killNum the value for game_detail.kill_num
     *
     * @mbggenerated
     */
    public void setKillNum(Integer killNum) {
        this.killNum = killNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_detail.score
     *
     * @return the value of game_detail.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_detail.score
     *
     * @param score the value for game_detail.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_detail.rank
     *
     * @return the value of game_detail.rank
     *
     * @mbggenerated
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_detail.rank
     *
     * @param rank the value for game_detail.rank
     *
     * @mbggenerated
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }
}