package com.ynhj.magic_war.model;

import java.util.Date;

public class RoleSkill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_skill.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_skill.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_skill.skill_id
     *
     * @mbggenerated
     */
    private Integer skillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_skill.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_skill.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_skill.keydown
     *
     * @mbggenerated
     */
    private String keydown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_skill.degree
     *
     * @mbggenerated
     */
    private Integer degree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_skill.id
     *
     * @return the value of role_skill.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_skill.id
     *
     * @param id the value for role_skill.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_skill.role_id
     *
     * @return the value of role_skill.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_skill.role_id
     *
     * @param roleId the value for role_skill.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_skill.skill_id
     *
     * @return the value of role_skill.skill_id
     *
     * @mbggenerated
     */
    public Integer getSkillId() {
        return skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_skill.skill_id
     *
     * @param skillId the value for role_skill.skill_id
     *
     * @mbggenerated
     */
    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_skill.create_time
     *
     * @return the value of role_skill.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_skill.create_time
     *
     * @param createTime the value for role_skill.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_skill.update_time
     *
     * @return the value of role_skill.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_skill.update_time
     *
     * @param updateTime the value for role_skill.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_skill.keydown
     *
     * @return the value of role_skill.keydown
     *
     * @mbggenerated
     */
    public String getKeydown() {
        return keydown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_skill.keydown
     *
     * @param keydown the value for role_skill.keydown
     *
     * @mbggenerated
     */
    public void setKeydown(String keydown) {
        this.keydown = keydown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_skill.degree
     *
     * @return the value of role_skill.degree
     *
     * @mbggenerated
     */
    public Integer getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_skill.degree
     *
     * @param degree the value for role_skill.degree
     *
     * @mbggenerated
     */
    public void setDegree(Integer degree) {
        this.degree = degree;
    }
}