package com.ynhj.magic_war.model;

import java.util.Date;

public class RoleEquipment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_equipment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_equipment.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_equipment.equipment_id
     *
     * @mbggenerated
     */
    private Integer equipmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_equipment.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_equipment.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_equipment.degree
     *
     * @mbggenerated
     */
    private Integer degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_equipment.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_equipment.id
     *
     * @return the value of role_equipment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_equipment.id
     *
     * @param id the value for role_equipment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_equipment.role_id
     *
     * @return the value of role_equipment.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_equipment.role_id
     *
     * @param roleId the value for role_equipment.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_equipment.equipment_id
     *
     * @return the value of role_equipment.equipment_id
     *
     * @mbggenerated
     */
    public Integer getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_equipment.equipment_id
     *
     * @param equipmentId the value for role_equipment.equipment_id
     *
     * @mbggenerated
     */
    public void setEquipmentId(Integer equipmentId) {
        this.equipmentId = equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_equipment.create_time
     *
     * @return the value of role_equipment.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_equipment.create_time
     *
     * @param createTime the value for role_equipment.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_equipment.status
     *
     * @return the value of role_equipment.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_equipment.status
     *
     * @param status the value for role_equipment.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_equipment.degree
     *
     * @return the value of role_equipment.degree
     *
     * @mbggenerated
     */
    public Integer getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_equipment.degree
     *
     * @param degree the value for role_equipment.degree
     *
     * @mbggenerated
     */
    public void setDegree(Integer degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_equipment.num
     *
     * @return the value of role_equipment.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_equipment.num
     *
     * @param num the value for role_equipment.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}