package com.ynhj.magic_war.model;

import java.util.Date;

public class Skill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.ui_url
     *
     * @mbggenerated
     */
    private String uiUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.before_time
     *
     * @mbggenerated
     */
    private Double beforeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.after_time
     *
     * @mbggenerated
     */
    private Double afterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.duration
     *
     * @mbggenerated
     */
    private Double duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.before_preb_url
     *
     * @mbggenerated
     */
    private String beforePrebUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.preb_url
     *
     * @mbggenerated
     */
    private String prebUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.after_preb_url
     *
     * @mbggenerated
     */
    private String afterPrebUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.range
     *
     * @mbggenerated
     */
    private Double range;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.cd
     *
     * @mbggenerated
     */
    private Double cd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.des
     *
     * @mbggenerated
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.id
     *
     * @return the value of skill.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.id
     *
     * @param id the value for skill.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.name
     *
     * @return the value of skill.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.name
     *
     * @param name the value for skill.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.ui_url
     *
     * @return the value of skill.ui_url
     *
     * @mbggenerated
     */
    public String getUiUrl() {
        return uiUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.ui_url
     *
     * @param uiUrl the value for skill.ui_url
     *
     * @mbggenerated
     */
    public void setUiUrl(String uiUrl) {
        this.uiUrl = uiUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.before_time
     *
     * @return the value of skill.before_time
     *
     * @mbggenerated
     */
    public Double getBeforeTime() {
        return beforeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.before_time
     *
     * @param beforeTime the value for skill.before_time
     *
     * @mbggenerated
     */
    public void setBeforeTime(Double beforeTime) {
        this.beforeTime = beforeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.after_time
     *
     * @return the value of skill.after_time
     *
     * @mbggenerated
     */
    public Double getAfterTime() {
        return afterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.after_time
     *
     * @param afterTime the value for skill.after_time
     *
     * @mbggenerated
     */
    public void setAfterTime(Double afterTime) {
        this.afterTime = afterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.duration
     *
     * @return the value of skill.duration
     *
     * @mbggenerated
     */
    public Double getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.duration
     *
     * @param duration the value for skill.duration
     *
     * @mbggenerated
     */
    public void setDuration(Double duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.before_preb_url
     *
     * @return the value of skill.before_preb_url
     *
     * @mbggenerated
     */
    public String getBeforePrebUrl() {
        return beforePrebUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.before_preb_url
     *
     * @param beforePrebUrl the value for skill.before_preb_url
     *
     * @mbggenerated
     */
    public void setBeforePrebUrl(String beforePrebUrl) {
        this.beforePrebUrl = beforePrebUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.preb_url
     *
     * @return the value of skill.preb_url
     *
     * @mbggenerated
     */
    public String getPrebUrl() {
        return prebUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.preb_url
     *
     * @param prebUrl the value for skill.preb_url
     *
     * @mbggenerated
     */
    public void setPrebUrl(String prebUrl) {
        this.prebUrl = prebUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.after_preb_url
     *
     * @return the value of skill.after_preb_url
     *
     * @mbggenerated
     */
    public String getAfterPrebUrl() {
        return afterPrebUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.after_preb_url
     *
     * @param afterPrebUrl the value for skill.after_preb_url
     *
     * @mbggenerated
     */
    public void setAfterPrebUrl(String afterPrebUrl) {
        this.afterPrebUrl = afterPrebUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.range
     *
     * @return the value of skill.range
     *
     * @mbggenerated
     */
    public Double getRange() {
        return range;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.range
     *
     * @param range the value for skill.range
     *
     * @mbggenerated
     */
    public void setRange(Double range) {
        this.range = range;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.cd
     *
     * @return the value of skill.cd
     *
     * @mbggenerated
     */
    public Double getCd() {
        return cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.cd
     *
     * @param cd the value for skill.cd
     *
     * @mbggenerated
     */
    public void setCd(Double cd) {
        this.cd = cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.type
     *
     * @return the value of skill.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.type
     *
     * @param type the value for skill.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.des
     *
     * @return the value of skill.des
     *
     * @mbggenerated
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.des
     *
     * @param des the value for skill.des
     *
     * @mbggenerated
     */
    public void setDes(String des) {
        this.des = des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.status
     *
     * @return the value of skill.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.status
     *
     * @param status the value for skill.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.create_time
     *
     * @return the value of skill.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.create_time
     *
     * @param createTime the value for skill.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.create_user
     *
     * @return the value of skill.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.create_user
     *
     * @param createUser the value for skill.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.update_time
     *
     * @return the value of skill.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.update_time
     *
     * @param updateTime the value for skill.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.update_user
     *
     * @return the value of skill.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.update_user
     *
     * @param updateUser the value for skill.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
}