package com.ynhj.magic_war.model;

import java.util.Date;

public class UserUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user-user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user-user.user1_id
     *
     * @mbggenerated
     */
    private String user1Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user-user.user2_id
     *
     * @mbggenerated
     */
    private String user2Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user-user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user-user.id
     *
     * @return the value of user-user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user-user.id
     *
     * @param id the value for user-user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user-user.user1_id
     *
     * @return the value of user-user.user1_id
     *
     * @mbggenerated
     */
    public String getUser1Id() {
        return user1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user-user.user1_id
     *
     * @param user1Id the value for user-user.user1_id
     *
     * @mbggenerated
     */
    public void setUser1Id(String user1Id) {
        this.user1Id = user1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user-user.user2_id
     *
     * @return the value of user-user.user2_id
     *
     * @mbggenerated
     */
    public String getUser2Id() {
        return user2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user-user.user2_id
     *
     * @param user2Id the value for user-user.user2_id
     *
     * @mbggenerated
     */
    public void setUser2Id(String user2Id) {
        this.user2Id = user2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user-user.create_time
     *
     * @return the value of user-user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user-user.create_time
     *
     * @param createTime the value for user-user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}